window.ANIMAL_WORLD = [
  {
    id: "lion",
    name: "非洲狮",
    latin: "Panthera leo",
    region: "非洲",
    habitat: "稀树草原",
    diet: "肉食",
    status: "易危",
    statusLevel: "vu",
    featured: true,
    image: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=700&q=70",
    summary: "草原上的社会性大型猫科，以狮群协作狩猎闻名。",
    story: "非洲狮是少数真正过群体生活的大型猫科。狮群通常由几头母狮、幼崽和一头或数头成年雄狮组成。母狮负责大部分狩猎，雄狮则以鬃毛和体型宣示领地。落日下的低吼可以传出数公里，那是非洲旷野最容易辨认的声音之一。",
    facts: ["肩高约 1.2 米", "吼声可传 8 公里", "主要猎物为斑马与角马"]
  },
  {
    id: "elephant",
    name: "非洲象",
    latin: "Loxodonta africana",
    region: "非洲",
    habitat: "草原 / 疏林",
    diet: "植食",
    status: "濒危",
    statusLevel: "en",
    featured: true,
    image: "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=700&q=70",
    summary: "陆地上最大的哺乳动物，象鼻既是鼻子，也是最灵巧的前肢。",
    story: "非洲象用象鼻饮水、卷枝、安抚幼象，甚至能分辨远处的雨云。母系家族由经验丰富的雌性族长带领，记忆中保存着水源和迁徙路线。长牙是延长的门齿，也因此让它们长期面临偷猎压力。",
    facts: ["体重可达 6 吨", "孕期约 22 个月", "日行数十公里寻找水源"]
  },
  {
    id: "giraffe",
    name: "长颈鹿",
    latin: "Giraffa camelopardalis",
    region: "非洲",
    habitat: "稀树草原",
    diet: "植食",
    status: "易危",
    statusLevel: "vu",
    image: "https://images.unsplash.com/photo-1547721064-8716ad6c0c0e?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1547721064-8716ad6c0c0e?auto=format&fit=crop&w=700&q=70",
    summary: "世界上最高的陆地动物，斑纹像指纹一样各不相同。",
    story: "长颈鹿用长舌卷取金合欢树冠上的嫩叶。为了把血液送到两米高的头部，它们拥有特别厚实的心脏和单向瓣膜。看似安静的散步，其实是在广阔领地里持续巡视食物与同伴。",
    facts: ["身高可达 5.5 米", "舌头约 45 厘米", "睡眠每天可能不足 2 小时"]
  },
  {
    id: "zebra",
    name: "斑马",
    latin: "Equus quagga",
    region: "非洲",
    habitat: "草原",
    diet: "植食",
    status: "近危",
    statusLevel: "nt",
    image: "https://images.unsplash.com/photo-1501706362039-c06b2d715385?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1501706362039-c06b2d715385?auto=format&fit=crop&w=700&q=70",
    summary: "黑白条纹既是伪装，也可能用来扰乱吸血昆虫。",
    story: "每一匹斑马的条纹排列都独一无二。迁徙季节，它们会与角马结成巨大的移动队伍，穿过河流和草原。条纹在热浪中晃动，能让狮群更难锁定单一个体。",
    facts: ["条纹如指纹般独特", "社群等级分明", "是塞伦盖蒂大迁徙成员"]
  },
  {
    id: "cheetah",
    name: "猎豹",
    latin: "Acinonyx jubatus",
    region: "非洲",
    habitat: "开阔草原",
    diet: "肉食",
    status: "易危",
    statusLevel: "vu",
    image: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=700&q=70",
    summary: "陆地短跑冠军，加速比多数跑车还快。",
    story: "猎豹的锁骨灵活、爪子半收缩，身体像一支被拉开的弓。一次全力冲刺后必须休息散热，因此狩猎窗口极短。泪痕般的面部条纹能减少眩光，帮助它们在正午锁定瞪羚。",
    facts: ["极速约 110 公里/小时", "3 秒内可加速到 100", "一次冲刺后需长时间休息"]
  },
  {
    id: "gorilla",
    name: "山地大猩猩",
    latin: "Gorilla beringei beringei",
    region: "非洲",
    habitat: "山地雨林",
    diet: "植食",
    status: "濒危",
    statusLevel: "en",
    image: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?auto=format&fit=crop&w=700&q=70",
    summary: "最接近人类的大型灵长类之一，银背雄性守护整个家族。",
    story: "山地大猩猩生活在中非高地的竹林与苔藓林中。银背雄性用胸口击打和低沉吼声维持秩序，但日常更多是安静地咀嚼茎叶。保护工作让它们从灭绝边缘缓慢回升，仍极度依赖完整的森林廊道。",
    facts: ["共享约 98% 人类基因", "家族由银背带领", "主要分布在维龙加火山区"]
  },
  {
    id: "flamingo",
    name: "火烈鸟",
    latin: "Phoenicopterus roseus",
    region: "非洲",
    habitat: "盐湖 / 浅滩",
    diet: "滤食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1497206365907-f5e630693df0?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1497206365907-f5e630693df0?auto=format&fit=crop&w=700&q=70",
    summary: "粉红色来自食物中的类胡萝卜素，是会走路的晚霞。",
    story: "火烈鸟倒立着头，用栉状喙过滤盐水中的藻类和甲壳动物。成千上万只聚集时，湖面会变成一片移动的珊瑚色。单脚站立能减少热量散失，也是它们最常被拍到的姿态。",
    facts: ["粉色来自食物色素", "喜集群繁殖", "喙是天然过滤器"]
  },
  {
    id: "panda",
    name: "大熊猫",
    latin: "Ailuropoda melanoleuca",
    region: "亚洲",
    habitat: "高山竹林",
    diet: "植食",
    status: "易危",
    statusLevel: "vu",
    featured: true,
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?auto=format&fit=crop&w=700&q=70",
    summary: "中国的伞护种明星，几乎只吃竹子，却仍是食肉目动物。",
    story: "大熊猫的“伪拇指”其实是腕骨特化，用来握住竹竿。它们每天要进食十多个小时，才能从低营养的竹子里提取足够能量。保护栖息地不仅救了熊猫，也保住了同一片山里的金丝猴、扭角羚和无数溪流。",
    facts: ["每天可吃 12–38 公斤竹", "属于熊科", "野外主要分布于四川等地"]
  },
  {
    id: "tiger",
    name: "东北虎",
    latin: "Panthera tigris altaica",
    region: "亚洲",
    habitat: "针阔混交林",
    diet: "肉食",
    status: "濒危",
    statusLevel: "en",
    featured: true,
    image: "https://images.unsplash.com/photo-1561731216-c3a0dcbb9670?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1561731216-c3a0dcbb9670?auto=format&fit=crop&w=700&q=70",
    summary: "体型最大的虎亚种，也是温带森林里的顶级猎手。",
    story: "东北虎需要广阔领地追踪鹿和野猪。厚密的被毛和宽大的爪垫让它们能在雪地潜行。一头虎的存在，往往说明整片森林的食物链仍然完整。",
    facts: ["体重可超 300 公斤", "夜行性较强", "每只虎的条纹独一无二"]
  },
  {
    id: "red-panda",
    name: "小熊猫",
    latin: "Ailurus fulgens",
    region: "亚洲",
    habitat: "高山阔叶林",
    diet: "植食为主",
    status: "濒危",
    statusLevel: "en",
    image: "https://images.unsplash.com/photo-1598439210625-5067eb638f3f?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1598439210625-5067eb638f3f?auto=format&fit=crop&w=700&q=70",
    summary: "不是大熊猫的幼崽，而是独立的“小猫熊”家族。",
    story: "小熊猫擅长爬树，白天常蜷在枝桠上睡觉，黄昏才出来觅食竹叶与浆果。锈红色的皮毛在苔藓林里像一块移动的秋叶。它们比大熊猫更少被看见，栖息地碎片化也更严重。",
    facts: ["单独成科", "尾巴可保暖与平衡", "分布横断山区至喜马拉雅"]
  },
  {
    id: "snow-leopard",
    name: "雪豹",
    latin: "Panthera uncia",
    region: "亚洲",
    habitat: "高山裸岩",
    diet: "肉食",
    status: "易危",
    statusLevel: "vu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.JPG/1280px-Irbis4.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.JPG/800px-Irbis4.JPG",
    summary: "高原幽灵，尾巴几乎与身体等长，用来在悬崖上保持平衡。",
    story: "雪豹沿着山脊和碎石坡追踪岩羊。灰白斑纹让它们融化在雪和岩石里，因此很少有人亲眼见过野生个体。牧民与雪豹的共存，是中亚保护工作里最关键的课题。",
    facts: ["尾长接近身长", "栖息海拔可超 5000 米", "一次可跃出 15 米"]
  },
  {
    id: "peacock",
    name: "蓝孔雀",
    latin: "Pavo cristatus",
    region: "亚洲",
    habitat: "林缘 / 农田",
    diet: "杂食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=700&q=70",
    summary: "开屏不是为了人类，而是雄鸟写给雌鸟的情书。",
    story: "蓝孔雀原产印度次大陆。雄鸟尾上覆羽展开时，眼斑会随光线变幻金属绿与宝蓝。开屏消耗能量，也更容易被天敌发现，因此这是一场关于健康与勇气的展示。",
    facts: ["尾屏可超 1.5 米", "叫声高亢传远", "被许多文化视为吉祥"]
  },
  {
    id: "crane",
    name: "丹顶鹤",
    latin: "Grus japonensis",
    region: "亚洲",
    habitat: "湿地",
    diet: "杂食",
    status: "易危",
    statusLevel: "vu",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Grus_japonensis_-Hokkaido%2C_Japan_-several-8.jpg/1280px-Grus_japonensis_-Hokkaido%2C_Japan_-several-8.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Grus_japonensis_-Hokkaido%2C_Japan_-several-8.jpg/800px-Grus_japonensis_-Hokkaido%2C_Japan_-several-8.jpg",
    summary: "东亚湿地的白色信使，求偶舞蹈像一场庄重的双人舞。",
    story: "丹顶鹤在浅水中觅食鱼虾和植物根茎。它们对湿地高度依赖，迁徙路线穿过东亚多处河口。头顶那一点朱红，是成鸟才有的标记。",
    facts: ["体长超过 1.4 米", "成对终生相伴", "繁殖于东北湿地"]
  },
  {
    id: "brown-bear",
    name: "棕熊",
    latin: "Ursus arctos",
    region: "欧洲",
    habitat: "山地森林",
    diet: "杂食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=700&q=70",
    summary: "从欧洲到西伯利亚都能见到的大型杂食者，嗅觉极其敏锐。",
    story: "棕熊会翻石头找昆虫，也会在秋季狂吃浆果和坚果为冬眠储备脂肪。欧洲残存的种群多生活在喀尔巴阡和斯堪的纳维亚的深山里，是荒野还在的证据。",
    facts: ["嗅觉远超猎犬", "冬眠可数月", "领地意识强但不主动攻击"]
  },
  {
    id: "red-fox",
    name: "赤狐",
    latin: "Vulpes vulpes",
    region: "欧洲",
    habitat: "林地 / 城市边缘",
    diet: "杂食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1474511323896-e8d5c187d69e?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1474511323896-e8d5c187d69e?auto=format&fit=crop&w=700&q=70",
    summary: "适应力极强的中型犬科，从森林走到了城市夜巷。",
    story: "赤狐会用跳跃扑击捕捉田鼠，耳朵能听见雪下的细微响动。在欧洲许多城镇，它们学会了夜间穿过花园。灵活、谨慎，又带着一点戏剧性的优雅。",
    facts: ["分布最广的犬科之一", "尾尖常为白色", "繁殖期会共用巢穴"]
  },
  {
    id: "lynx",
    name: "欧亚猞猁",
    latin: "Lynx lynx",
    region: "欧洲",
    habitat: "针叶林",
    diet: "肉食",
    status: "无危",
    statusLevel: "lc",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Lynx_lynx2.jpg/1280px-Lynx_lynx2.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Lynx_lynx2.jpg/800px-Lynx_lynx2.jpg",
    summary: "耳尖簇毛和厚爪垫，是为雪林准备的静音猎手。",
    story: "猞猁喜欢独自埋伏，主要捕食狍和野兔。耳尖的黑色簇毛能帮助判断声音方向。在重新野化的欧洲森林里，它们的回归意味着中型猎物重新有了自然调控者。",
    facts: ["后足宽大适于雪地", "黄昏与夜间活动", "一次可跨越数米"]
  },
  {
    id: "red-deer",
    name: "马鹿",
    latin: "Cervus elaphus",
    region: "欧洲",
    habitat: "林缘草地",
    diet: "植食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1484406566174-9da000fda645?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1484406566174-9da000fda645?auto=format&fit=crop&w=700&q=70",
    summary: "秋天薄雾山谷里，雄鹿的吼声是求偶季节的号角。",
    story: "马鹿雄性每年重新长出鹿角，并在发情季用角力和长啸争夺群体。它们塑造林缘植被，也是狼和猞猁的重要猎物，把森林食物网连在一起。",
    facts: ["雄性每年换角", "群居雌性带领幼崽", "分布横跨欧亚"]
  },
  {
    id: "bison",
    name: "美洲野牛",
    latin: "Bison bison",
    region: "北美洲",
    habitat: "草原",
    diet: "植食",
    status: "近危",
    statusLevel: "nt",
    featured: true,
    image: "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?auto=format&fit=crop&w=700&q=70",
    summary: "北美草原曾经的主人，厚肩与头骨能推开冬雪找草。",
    story: "美洲野牛一度数以千万计，几乎定义了大平原的生态。翻拱土地、传播种子、为草原制造镶嵌生境。今天的恢复项目正在把它们重新带回原野，也带回原住民文化叙事的中心。",
    facts: ["肩高可超 1.8 米", "冬季靠头拱雪觅食", "是北美最大陆生哺乳动物"]
  },
  {
    id: "bald-eagle",
    name: "白头海雕",
    latin: "Haliaeetus leucocephalus",
    region: "北美洲",
    habitat: "河湖海岸",
    diet: "肉食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1611689342806-086263b657c0?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1611689342806-086263b657c0?auto=format&fit=crop&w=700&q=70",
    summary: "美国的象征猛禽，从农药危机中被保护行动拉了回来。",
    story: "白头海雕喜欢沿着河流筑巨大的巢，一对配偶会多年沿用并不断加高。DDT 曾让它们的蛋壳变薄，禁令与栖息地保护让种群显著恢复，成为现代保育最常被讲述的成功故事之一。",
    facts: ["翼展超过 2 米", "主食鱼类", "成鸟头部才变白"]
  },
  {
    id: "grey-wolf",
    name: "灰狼",
    latin: "Canis lupus",
    region: "北美洲",
    habitat: "森林 / 苔原",
    diet: "肉食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1602491453631-e2a5ad90a97c?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1602491453631-e2a5ad90a97c?auto=format&fit=crop&w=700&q=70",
    summary: "高度社会性的顶级捕食者，嚎叫用来召集同伴和划分领地。",
    story: "灰狼以家庭式狼群协作围猎鹿和麋。黄石公园重新引入狼之后，植被、河流形态和整个食物网都发生了连锁变化。它们提醒人们：一种动物可以改写一片风景。",
    facts: ["狼群有明确分工", "嚎叫可传数公里", "一次行程能跑出很远"]
  },
  {
    id: "raccoon",
    name: "浣熊",
    latin: "Procyon lotor",
    region: "北美洲",
    habitat: "林地 / 城市",
    diet: "杂食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1497752531616-c3af1da0d214?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1497752531616-c3af1da0d214?auto=format&fit=crop&w=700&q=70",
    summary: "前掌极度灵敏，被称作“长着手的面具侠”。",
    story: "浣熊喜欢在水边翻找甲壳和蛙类，城市里则学会打开垃圾桶。黑眼罩不是伪装罪犯，而是帮助减少眩光。聪明、好奇，也因此更容易和人类生活重叠。",
    facts: ["前掌触觉极发达", "夜行性", "适应城市能力强"]
  },
  {
    id: "jaguar",
    name: "美洲豹",
    latin: "Panthera onca",
    region: "南美洲",
    habitat: "热带雨林",
    diet: "肉食",
    status: "近危",
    statusLevel: "nt",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Junior-Jaguar-Belize-Zoo.jpg/1280px-Junior-Jaguar-Belize-Zoo.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Junior-Jaguar-Belize-Zoo.jpg/800px-Junior-Jaguar-Belize-Zoo.jpg",
    summary: "美洲最强的猫科，咬合力足以咬穿龟壳和头骨。",
    story: "美洲豹沿河岸巡猎，既能游泳也能爬树。它们的斑点是玫瑰形，中心常有更小的点。 Intact 的亚马孙河岸对它们至关重要——失去廊道，等于切断一只豹的一生。",
    facts: ["咬合力在猫科中极强", "擅长捕鱼与伏击", "玫瑰斑区别于豹"]
  },
  {
    id: "sloth",
    name: "树懒",
    latin: "Bradypus variegatus",
    region: "南美洲",
    habitat: "雨林树冠",
    diet: "植食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1504006833117-8886a196d390?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1504006833117-8886a196d390?auto=format&fit=crop&w=700&q=70",
    summary: "把生命节奏降到树叶生长的速度，毛发里甚至住着藻类。",
    story: "树懒一周可能只下树一次，为的是在地面排便。缓慢代谢让它们能靠低热量树叶生存。毛发沟壑里的藻类带来绿色伪装，也形成一座微型雨林。",
    facts: ["每周约下树一次", "毛发可共生藻类", "几乎终生倒挂"]
  },
  {
    id: "alpaca",
    name: "羊驼",
    latin: "Vicugna pacos",
    region: "南美洲",
    habitat: "高原草地",
    diet: "植食",
    status: "家养",
    statusLevel: "dom",
    image: "https://images.unsplash.com/photo-1589182337358-2cb63099350c?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1589182337358-2cb63099350c?auto=format&fit=crop&w=700&q=70",
    summary: "安第斯高原上的同伴动物，绒毛轻暖，表情永远像在思考人生。",
    story: "羊驼由美洲原住民驯化，用于产毛而非负重。它们以轻柔的脚步走过高海拔草场，对植被破坏较小。今天既是高原文化的一部分，也成为世界各地农场里的温和明星。",
    facts: ["绒毛细软保暖", "社群靠哼鸣交流", "原产安第斯山脉"]
  },
  {
    id: "macaw",
    name: "金刚鹦鹉",
    latin: "Ara macao",
    region: "南美洲",
    habitat: "雨林",
    diet: "植食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1549608276-5786777e6587?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1549608276-5786777e6587?auto=format&fit=crop&w=700&q=70",
    summary: "雨林里最响亮的颜色，成对飞行时像两支燃烧的箭。",
    story: "绯红金刚鹦鹉用强喙剖开坚果，成对终身相伴。粘土舔食场是它们补充矿物质的社交场所。宠物贸易曾经重创一些种群，野生个体更需要连片树冠。",
    facts: ["寿命可超 50 年", "成对活动", "喙能打开坚硬种子"]
  },
  {
    id: "capybara",
    name: "水豚",
    latin: "Hydrochoerus hydrochaeris",
    region: "南美洲",
    habitat: "湿地",
    diet: "植食",
    status: "无危",
    statusLevel: "lc",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Capybara_%28Hydrochoerus_hydrochaeris%29.JPG/1280px-Capybara_%28Hydrochoerus_hydrochaeris%29.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Capybara_%28Hydrochoerus_hydrochaeris%29.JPG/800px-Capybara_%28Hydrochoerus_hydrochaeris%29.JPG",
    summary: "世界最大的啮齿动物，半水栖，社交能力强到能和几乎所有动物和平共处。",
    story: "水豚眼、耳、鼻都长在头顶，适合只露出水面观察。它们成群在河岸啃草，遇到危险就滑入水中。温和的性格让它们成为南美湿地的“公共沙发”。",
    facts: ["体重可达 60 公斤以上", "趾间有蹼", "高度社群化"]
  },
  {
    id: "kangaroo",
    name: "红袋鼠",
    latin: "Osphranter rufus",
    region: "大洋洲",
    habitat: "干旱草原",
    diet: "植食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=700&q=70",
    summary: "用尾巴当第三条腿，跳跃是为了在干热大陆上高效移动。",
    story: "红袋鼠是澳大利亚内陆的象征。雌性育儿袋让幼崽在未发育完全时就能继续生长。干旱来临时，它们能延缓繁殖，把生命节奏交给降雨。",
    facts: ["一次跳跃可超 8 米", "尾巴可支撑身体", "澳洲体型最大的袋鼠"]
  },
  {
    id: "koala",
    name: "考拉",
    latin: "Phascolarctos cinereus",
    region: "大洋洲",
    habitat: "桉树林",
    diet: "植食",
    status: "易危",
    statusLevel: "vu",
    image: "https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?auto=format&fit=crop&w=700&q=70",
    summary: "几乎只吃桉树叶，因此大部分时间都在睡觉以节省能量。",
    story: "考拉的肝脏能处理桉叶中的毒素，代价是极低的代谢。野火和栖息地破碎让它们变得更脆弱。一对绒耳和黑鼻子让人想拥抱，但野生个体需要的是连片的树廊。",
    facts: ["每天睡 18–20 小时", "指纹与人类相似", "幼崽要吃“育儿粪便”建立菌群"]
  },
  {
    id: "platypus",
    name: "鸭嘴兽",
    latin: "Ornithorhynchus anatinus",
    region: "大洋洲",
    habitat: "溪流",
    diet: "肉食",
    status: "近危",
    statusLevel: "nt",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Platypus_in_creek.jpg/1280px-Platypus_in_creek.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Platypus_in_creek.jpg/800px-Platypus_in_creek.jpg",
    summary: "卵生哺乳动物，喙能感知水中猎物的电场。",
    story: "当第一只鸭嘴兽标本送到欧洲，博物学家以为有人把鸭子和海狸缝在了一起。它产卵、泌乳、雄性踝部还有毒刺。澳大利亚东部的清澈溪流，是这种“不可能动物”最后的舞台。",
    facts: ["单孔目动物", "闭眼靠电感觉捕食", "雄性有毒距"]
  },
  {
    id: "emu",
    name: "鸸鹋",
    latin: "Dromaius novaehollandiae",
    region: "大洋洲",
    habitat: "疏林草原",
    diet: "杂食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=700&q=70",
    summary: "澳洲最高的鸟，不会飞，但奔跑起来能追上自行车。",
    story: "鸸鹋由雄鸟孵卵并带领幼雏。它们能长途行走寻找降雨后的新芽。国徽上与袋鼠并列，象征这个大陆上那些选择用双腿而非翅膀征服距离的生命。",
    facts: ["身高约 1.9 米", "雄鸟育幼", "奔跑时速可超 50 公里"]
  },
  {
    id: "polar-bear",
    name: "北极熊",
    latin: "Ursus maritimus",
    region: "极地海洋",
    habitat: "海冰",
    diet: "肉食",
    status: "易危",
    statusLevel: "vu",
    featured: true,
    image: "https://images.unsplash.com/photo-1589656966895-2d91cc4e1d7b?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1589656966895-2d91cc4e1d7b?auto=format&fit=crop&w=700&q=70",
    summary: "海冰上的旅行者，命运与北极夏季冰面的存续绑在一起。",
    story: "北极熊大部分时间在海上度过，等待海豹从呼吸孔出现。毛发中空，皮肤却近乎黑色，为的是锁住每一分光和热。海冰提前融化，意味着更长的饥饿季节。",
    facts: ["最大的陆地食肉动物之一", "嗅觉可隔冰侦测海豹", "被毛下是黑色皮肤"]
  },
  {
    id: "penguin",
    name: "帝企鹅",
    latin: "Aptenodytes forsteri",
    region: "极地海洋",
    habitat: "南极海冰",
    diet: "肉食",
    status: "近危",
    statusLevel: "nt",
    featured: true,
    image: "https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?auto=format&fit=crop&w=700&q=70",
    summary: "南极冬季由雄鸟孵卵，用身体围成旋转的保温圈。",
    story: "帝企鹅是体型最大的企鹅。雌鸟产卵后出海觅食，雄鸟把卵放在脚背上，盖着育儿袋熬过极夜。群体会缓慢轮转，让外侧的个体也能进入温暖中心。",
    facts: ["潜深可超 500 米", "雄鸟负责冬季孵卵", "身高约 1.2 米"]
  },
  {
    id: "blue-whale",
    name: "蓝鲸",
    latin: "Balaenoptera musculus",
    region: "极地海洋",
    habitat: "远洋",
    diet: "滤食",
    status: "濒危",
    statusLevel: "en",
    featured: true,
    image: "https://images.unsplash.com/photo-1568430462989-44163eb1751f?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1568430462989-44163eb1751f?auto=format&fit=crop&w=700&q=70",
    summary: "地球上有记录以来最大的动物，一次吞咽就能过滤一整片磷虾云。",
    story: "蓝鲸的心脏有小汽车那么大，低频率歌声能穿越海洋盆地。商业捕鲸曾把它们推向崩溃，禁捕后部分种群缓慢回升。看见一道蓝灰色背脊出水，等于看见地球还愿意把最大的房间留给野生生命。",
    facts: ["体长可超 30 米", "主食磷虾", "歌声能传极远距离"]
  },
  {
    id: "dolphin",
    name: "宽吻海豚",
    latin: "Tursiops truncatus",
    region: "极地海洋",
    habitat: "近海",
    diet: "肉食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1607153333879-c174d265f1d2?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1607153333879-c174d265f1d2?auto=format&fit=crop&w=700&q=70",
    summary: "会用名字哨音称呼同伴的海洋哺乳动物。",
    story: "宽吻海豚以回声定位猎鱼，也能合作把鱼群赶向浅滩。研究者记录到个体专属的哨音，类似名字。近岸水质、渔网和航运噪音，是它们最日常的威胁。",
    facts: ["使用回声定位", "高度社会性", "分布于全球温带与热带近海"]
  },
  {
    id: "turtle",
    name: "绿海龟",
    latin: "Chelonia mydas",
    region: "极地海洋",
    habitat: "珊瑚海 / 沙滩",
    diet: "植食为主",
    status: "濒危",
    statusLevel: "en",
    image: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?auto=format&fit=crop&w=700&q=70",
    summary: "穿越整个大洋去产卵的古老航海者，出生海滩往往就是回归地。",
    story: "雌性绿海龟会回到自己出生的沙滩挖坑产卵。幼龟破壳后凭借月光走向海浪，路上充满天敌。保护灯光管制和减少塑料，是把航线还给它们的最小动作。",
    facts: ["迁徙可跨数千公里", "成体主要吃海草", "温度决定幼体性别"]
  },
  {
    id: "shark",
    name: "大白鲨",
    latin: "Carcharodon carcharias",
    region: "极地海洋",
    habitat: "大陆架海域",
    diet: "肉食",
    status: "易危",
    statusLevel: "vu",
    image: "https://images.unsplash.com/photo-1560275619-4cc5fa59d10b?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1560275619-4cc5fa59d10b?auto=format&fit=crop&w=700&q=70",
    summary: "海洋食物网的修剪者，感官能察觉远处一滴血的化学信号。",
    story: "大白鲨并非电影里的复仇机器。它们追踪海豹集群，也会长途迁徙到开阔大洋。失去鲨鱼，意味着中层鱼类和生态系统失衡。害怕它们很容易，理解它们更难，也更必要。",
    facts: ["能感应电场", "牙齿可终身替换", "部分个体跨洋迁徙"]
  },
  {
    id: "owl",
    name: "仓鸮",
    latin: "Tyto alba",
    region: "欧洲",
    habitat: "农田 / 谷仓",
    diet: "肉食",
    status: "无危",
    statusLevel: "lc",
    image: "https://images.unsplash.com/photo-1553264701-d13871843174?auto=format&fit=crop&w=1400&q=80",
    thumb: "https://images.unsplash.com/photo-1553264701-d13871843174?auto=format&fit=crop&w=700&q=70",
    summary: "心形面盘是天然雷达，让它能在全黑中捕捉田鼠。",
    story: "仓鸮的羽毛边缘呈梳状，飞行几乎无声。它们是农田生态系统的免费捕鼠者。旧谷仓和树洞减少后，人工巢箱成为很多地区把它们留住的方法。",
    facts: ["飞行近乎无声", "面盘汇聚声波", "全球分布最广的鸮类之一"]
  }
];
